services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.9.1
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    networks:
      - prometheus_grafana_network
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave

networks:
  prometheus_grafana_network:
    external: true
